import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import { AppState } from 'react-native';

import type { CardDesign } from '@/constants/card-styles';
import type { IconName } from '@/constants/categories';
import { useAuth } from '@/context/AuthContext';
import { useSettings } from '@/context/SettingsContext';
import { cycleOf } from '@/utils/cycle';
import { monthShort, weekdayShort } from '@/i18n/format';
import { usePersistedState } from '@/hooks/use-persisted-state';
import { savedEntries } from '@/utils/saved';
import { confirmedTransaction, confirmedTransfer, isTransfer, materializeRecurring, skipToUpcoming } from '@/utils/recurring';


export type TransactionType = 'debit' | 'credit';

export type AccountType = 'bank' | 'cash' | 'savings' | 'other';

export type Account = {
  id: string;
  name: string;
  type: AccountType;
  /** Name of a user-made type (stored with type 'other'); shown instead of the built-in label. */
  typeLabel?: string;
  icon: IconName;
  initialBalance: number; // starting balance before any tracked transactions
  // Card look + optional details (all optional so older accounts keep working)
  color?: string; // hex, e.g. '#2563EB'
  design?: CardDesign;
  provider?: string; // e.g. 'Maybank', 'TNG eWallet'
  last4?: string; // last 4 digits only, never a full number
  /** Set on the account WaKira makes for a debt (see Hutang). Money owed shows up as a negative balance here. */
  debtId?: string;
  /** Internal debt accounts (instalments, loans) are kept out of pickers, the card carousel and the Home total. */
  hidden?: boolean;
  /** PayLater-style accounts: the spending limit. Money used = the negative balance. */
  creditLimit?: number;
};

export type TransactionItem = { id: string; label: string; amount: number };

export type Transaction = {
  id: string;
  title: string;
  date: string;
  categoryId: string;
  subcategory: string;
  amount: number;
  type: TransactionType;
  accountId: string;
  /** Optional line items, e.g. Nasi Lemak RM5, Service Charge RM0.50. */
  items?: TransactionItem[];
  /** Set when this transaction was generated by a recurring rule. */
  recurringId?: string;
  /** Set when this transaction belongs to a debt (an instalment's interest or fee). */
  debtId?: string;
};

/**
 * Money moved between two of the user's own accounts.
 * Deliberately NOT a Transaction: it changes each account's balance but is never
 * income or spending, so it can't distort budgets, charts or monthly totals.
 */
export type Transfer = {
  id: string;
  fromAccountId: string;
  toAccountId: string;
  amount: number;
  date: string; // YYYY-MM-DD
  note?: string;
  /** Set when this transfer was generated by a recurring rule. */
  recurringId?: string;
  /** Set when this transfer pays a debt or pays out a loan. */
  debtId?: string;
  /** Set when the transfer is savings that should count against this category's budget (see utils/saved.ts). */
  budgetCategoryId?: string;
  budgetSub?: string;
  /** Set when the transfer is money put toward a savings goal (see utils/goals.ts). */
  goalId?: string;
};

export type RecurringFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

/**
 * fixed = the same amount is recorded automatically on each date.
 * ask   = on each date an entry WAITS for the user to type the real amount (salary that changes, utility bills).
 */
export type RecurringAmountMode = 'fixed' | 'ask';

/** A schedule that creates a real transaction each time it falls due. */
export type RecurringRule = {
  id: string;
  title: string;
  /**
   * Missing = an ordinary income/expense rule. 'transfer' = moves `amount` from `accountId` to `toAccountId`
   * (never income or spending, so it has no category and is left out of bills and the monthly commitment).
   */
  kind?: 'transaction' | 'transfer';
  /** Transfer rules only: the account the money goes to. `accountId` is then the account it leaves. */
  toAccountId?: string;
  /** Fixed rules: the amount recorded. 'ask' rules: only an optional expected amount (0 = unknown). */
  amount: number;
  /** Missing on rules saved before this existed, which means 'fixed'. */
  amountMode?: RecurringAmountMode;
  type: TransactionType;
  categoryId: string;
  subcategory: string;
  accountId: string;
  frequency: RecurringFrequency;
  /** First occurrence. Also the anchor for "day of month" on monthly/yearly rules. */
  startDate: string;
  /** The next occurrence that has NOT been turned into a transaction yet. */
  nextDate: string;
  /** Optional last date (inclusive). */
  endDate?: string;
  active: boolean;
  /** Set on a transfer rule made by a savings goal's "save automatically" option. */
  goalId?: string;
};

/**
 * A due occurrence of an 'ask' rule, waiting for the real amount.
 * It is NOT a transaction: it never touches balances, budgets or charts until the user confirms it.
 */
export type PendingEntry = { id: string; ruleId: string; date: string };

export type ChartPeriod = 'week' | 'month' | 'year';

export type ChartPoint = {
  key: string;
  label: string;
  value: number;
  /** true when this point represents "today" (only ever set for week points) */
  isToday?: boolean;
  isFuture?: boolean;
};

type TransactionsContextValue = {
  /** True once transactions, recurring rules and pending entries are all loaded from storage. */
  ready: boolean;
  transactions: Transaction[];
  addTransaction: (t: Omit<Transaction, 'id'>) => string;
  /** Adds many at once (file import). Returns the new ids so the import can be undone. */
  addTransactions: (list: Omit<Transaction, 'id'>[]) => string[];
  deleteTransactions: (ids: string[]) => void;
  updateTransaction: (id: string, patch: Partial<Omit<Transaction, 'id'>>) => void;
  deleteTransaction: (id: string) => void;
  /** Put back a record that was just deleted (same id), for Undo. */
  restoreTransaction: (t: Transaction) => void;
  reassignCategory: (fromId: string, toId: string) => void;
  balance: number;
  spentThisMonth: (categoryId: string) => number;
  /** Transactions plus savings transfers that count in the budget. Use this to measure budgets, never for income or spending totals. */
  budgetEntries: Transaction[];
  totalIncomeThisMonth: () => number;
  totalSpendingThisMonth: () => number;
  categoryBreakdownThisMonth: () => { categoryId: string; value: number; percent: number }[];
  /** Pass `accountId` to limit the list to one account (omit for all accounts). */
  recentTransactions: (count?: number, accountId?: string) => Transaction[];
  /** weekOffset: 0 = the week containing today, -1 = the week before that, etc. `accountId` limits to one account. */
  getWeekChartData: (weekOffset: number, accountId?: string) => ChartPoint[];
  /** Jan -> Dec of the current year */
  getMonthChartData: (accountId?: string) => ChartPoint[];
  /** one point per calendar year that has data (current year always included) */
  getYearChartData: (accountId?: string) => ChartPoint[];

  // Accounts (bank, cash, etc.)
  /** Every account, including the internal ones WaKira makes for debts. */
  accounts: Account[];
  /** The accounts a person can pick: everything except internal debt accounts. */
  selectableAccounts: Account[];
  addAccount: (a: Omit<Account, 'id'>) => void;
  addAccounts: (list: Omit<Account, 'id'>[]) => string[];
  updateAccount: (id: string, patch: Partial<Omit<Account, 'id'>>) => void;
  /** Deletes the account and any transactions tied to it. */
  deleteAccount: (id: string) => void;
  /** New order for the accounts shown in lists and the card carousel. Hidden accounts keep their place. */
  reorderAccounts: (orderedVisibleIds: string[]) => void;
  accountBalance: (accountId: string) => number;
  /** Every account paired with its current computed balance — handy for the Assets tab. */
  accountBalances: () => (Account & { balance: number })[];

  // Transfers between accounts
  transfers: Transfer[];
  addTransfer: (t: Omit<Transfer, 'id'>) => string;
  updateTransfer: (id: string, patch: Partial<Omit<Transfer, 'id'>>) => void;
  deleteTransfer: (id: string) => void;
  restoreTransfer: (t: Transfer) => void;

  // Recurring rules (transactions are generated automatically when they fall due)
  recurringRules: RecurringRule[];
  addRecurring: (r: Omit<RecurringRule, 'id'>) => string;
  updateRecurring: (id: string, patch: Partial<Omit<RecurringRule, 'id'>>) => void;
  deleteRecurring: (id: string) => void;
  /** Pause or resume. Resuming skips the paused period instead of back-filling it. */
  setRecurringActive: (id: string, active: boolean) => void;

  /** Due 'ask' occurrences waiting for the real amount. */
  pendingEntries: PendingEntry[];
  /** Records the real amount (and the date it actually arrived) and removes the entry. */
  confirmPending: (id: string, amount: number, date: string) => void;
  /** Drops the entry without recording anything (e.g. no salary this month). */
  dismissPending: (id: string) => void;

  resetAllData: () => void;
};

const TransactionsContext = createContext<TransactionsContextValue | undefined>(undefined);

const initialAccounts: Account[] = [
  { id: 'bank', name: 'Bank', type: 'bank', icon: 'business', initialBalance: 0 }, // i18n-ignore: stored default name; shown via accountName()
  { id: 'cash', name: 'Cash', type: 'cash', icon: 'cash', initialBalance: 0 }, // i18n-ignore: stored default name; shown via accountName()
];

const initialTransactions: Transaction[] = [];

let idCounter = 0;
/** Unique even when several records are made in the same millisecond. */
function newId(prefix: string) {
  idCounter += 1;
  return `${prefix}${Date.now()}${idCounter > 1 ? `_${idCounter}` : ''}`;
}

// Local-date key (avoids the UTC-shift you get from toISOString() near midnight).
function toDateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// Monday of the week containing `d`.
function startOfWeek(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay(); // 0 = Sun ... 6 = Sat
  const diffToMonday = day === 0 ? -6 : 1 - day;
  date.setDate(date.getDate() + diffToMonday);
  date.setHours(0, 0, 0, 0);
  return date;
}

export function TransactionsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const { paydayRuleKey } = useSettings();
  const [storedTransactions, setTransactions, transactionsReady] = usePersistedState<Transaction[]>('transactions', initialTransactions, user?.id ?? null);
  // A new array whenever the payday changes, so everything derived from the records (monthly totals, budgets,
  // charts) is worked out again for the new financial month. The records themselves are untouched.
  const transactions = useMemo(() => (paydayRuleKey ? [...storedTransactions] : storedTransactions), [storedTransactions, paydayRuleKey]);
  const [accounts, setAccounts, accountsReady] = usePersistedState<Account[]>('accounts', initialAccounts, user?.id ?? null);
  const [transfers, setTransfers, transfersReady] = usePersistedState<Transfer[]>('transfers', [], user?.id ?? null);
  const [recurringRules, setRecurringRules, recurringReady] = usePersistedState<RecurringRule[]>('recurring', [], user?.id ?? null);
  const [pendingEntries, setPendingEntries, pendingReady] = usePersistedState<PendingEntry[]>('pending', [], user?.id ?? null);

  // Changes when the app returns to the foreground on a new day, so due rules are picked up
  // even if the app was left open overnight.
  const [todayKey, setTodayKey] = useState(() => toDateKey(new Date()));
  useEffect(() => {
    const sub = AppState.addEventListener('change', (state) => {
      if (state === 'active') setTodayKey(toDateKey(new Date()));
    });
    return () => sub.remove();
  }, []);

  // Turn due recurring occurrences into real transactions (fixed rules) or pending entries ('ask' rules).
  // Recurring transfer rules create transfers instead of transactions.
  // Waits until ALL FOUR lists have been loaded from storage: generating earlier would be overwritten by
  // the load that finishes afterwards.
  useEffect(() => {
    if (!transactionsReady || !recurringReady || !pendingReady || !transfersReady) return;
    const { rules, created, pending, transfers: madeTransfers } = materializeRecurring(recurringRules, transactions, todayKey, pendingEntries, transfers);
    if (created.length === 0 && pending.length === 0 && madeTransfers.length === 0 && rules === recurringRules) return;
    if (madeTransfers.length > 0) {
      setTransfers((prev) => {
        const have = new Set(prev.map((t) => t.id));
        const fresh = madeTransfers.filter((t) => !have.has(t.id));
        return fresh.length > 0 ? [...fresh, ...prev] : prev;
      });
    }
    if (created.length > 0) {
      setTransactions((prev) => {
        const have = new Set(prev.map((t) => t.id));
        const fresh = created.filter((t) => !have.has(t.id));
        return fresh.length > 0 ? [...fresh, ...prev] : prev;
      });
    }
    if (pending.length > 0) {
      setPendingEntries((prev) => {
        const have = new Set(prev.map((p) => p.id));
        const fresh = pending.filter((p) => !have.has(p.id));
        return fresh.length > 0 ? [...prev, ...fresh] : prev;
      });
    }
    setRecurringRules(rules);
  }, [
    transactionsReady,
    recurringReady,
    pendingReady,
    transfersReady,
    recurringRules,
    transactions,
    pendingEntries,
    transfers,
    todayKey,
    setTransfers,
    setTransactions,
    setPendingEntries,
    setRecurringRules,
  ]);

  function addTransaction(t: Omit<Transaction, 'id'>) {
    const id = newId('');
    setTransactions((prev) => [{ ...t, id }, ...prev]);
    return id;
  }

  function addTransactions(list: Omit<Transaction, 'id'>[]) {
    const stamp = Date.now();
    const ids = list.map((_, i) => `imp_${stamp}_${i}`);
    setTransactions((prev) => [...list.map((t, i) => ({ ...t, id: ids[i] })), ...prev]);
    return ids;
  }

  function deleteTransactions(ids: string[]) {
    const gone = new Set(ids);
    setTransactions((prev) => prev.filter((t) => !gone.has(t.id)));
  }

  function updateTransaction(id: string, patch: Partial<Omit<Transaction, 'id'>>) {
    setTransactions((prev) => prev.map((t) => (t.id === id ? { ...t, ...patch } : t)));
  }

  function deleteTransaction(id: string) {
    setTransactions((prev) => prev.filter((t) => t.id !== id));
  }

  function restoreTransaction(tx: Transaction) {
    setTransactions((prev) => (prev.some((t) => t.id === tx.id) ? prev : [tx, ...prev]));
  }

  function restoreTransfer(tr: Transfer) {
    setTransfers((prev) => (prev.some((t) => t.id === tr.id) ? prev : [tr, ...prev]));
  }

  function reorderAccounts(orderedVisibleIds: string[]) {
    setAccounts((prev) => {
      const byId = new Map(prev.map((a) => [a.id, a]));
      const queue = orderedVisibleIds.map((id) => byId.get(id)).filter((a): a is Account => !!a);
      const visibleIds = new Set(prev.filter((a) => !a.hidden).map((a) => a.id));
      // Same slots as before; each visible slot takes the next account in the new order.
      let i = 0;
      const next = prev.map((a) => (a.hidden || !visibleIds.has(a.id) ? a : (queue[i++] ?? a)));
      return next.length === prev.length && new Set(next.map((a) => a.id)).size === prev.length ? next : prev;
    });
  }

  function reassignCategory(fromId: string, toId: string) {
    setTransactions((prev) => prev.map((t) => (t.categoryId === fromId ? { ...t, categoryId: toId } : t)));
  }

  function addAccount(a: Omit<Account, 'id'>) {
    setAccounts((prev) => [...prev, { ...a, id: Date.now().toString() }]);
  }

  function addAccounts(list: Omit<Account, 'id'>[]) {
    const stamp = Date.now();
    const ids = list.map((_, i) => `acc_${stamp}_${i}`);
    setAccounts((prev) => [...prev, ...list.map((a, i) => ({ ...a, id: ids[i] }))]);
    return ids;
  }

  function updateAccount(id: string, patch: Partial<Omit<Account, 'id'>>) {
    setAccounts((prev) => prev.map((acc) => (acc.id === id ? { ...acc, ...patch } : acc)));
  }

  function deleteAccount(id: string) {
    setAccounts((prev) => prev.filter((acc) => acc.id !== id));
    setTransactions((prev) => prev.filter((t) => t.accountId !== id));
    // A transfer needs both accounts, and a rule needs its account to post into.
    setTransfers((prev) => prev.filter((t) => t.fromAccountId !== id && t.toAccountId !== id));
    const touches = (r: RecurringRule) => r.accountId === id || r.toAccountId === id;
    const orphanRuleIds = new Set(recurringRules.filter(touches).map((r) => r.id));
    setRecurringRules((prev) => prev.filter((r) => !touches(r)));
    setPendingEntries((prev) => prev.filter((p) => !orphanRuleIds.has(p.ruleId)));
  }

  function addTransfer(t: Omit<Transfer, 'id'>) {
    const id = newId('tr_');
    setTransfers((prev) => [{ ...t, id }, ...prev]);
    return id;
  }

  function updateTransfer(id: string, patch: Partial<Omit<Transfer, 'id'>>) {
    setTransfers((prev) => prev.map((t) => (t.id === id ? { ...t, ...patch } : t)));
  }

  function deleteTransfer(id: string) {
    setTransfers((prev) => prev.filter((t) => t.id !== id));
  }

  function addRecurring(r: Omit<RecurringRule, 'id'>) {
    const id = `rule_${Date.now()}_${Math.random().toString(36).slice(2, 5)}`;
    setRecurringRules((prev) => [...prev, { ...r, id }]);
    return id;
  }

  function updateRecurring(id: string, patch: Partial<Omit<RecurringRule, 'id'>>) {
    setRecurringRules((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  }

  // Deleting a rule keeps the transactions it already created: they are real history.
  function deleteRecurring(id: string) {
    setRecurringRules((prev) => prev.filter((r) => r.id !== id));
    setPendingEntries((prev) => prev.filter((p) => p.ruleId !== id));
  }

  function confirmPending(id: string, amount: number, date: string) {
    const entry = pendingEntries.find((p) => p.id === id);
    const rule = entry ? recurringRules.find((r) => r.id === entry.ruleId) : undefined;
    if (!entry || !rule || !(amount > 0)) return;
    if (isTransfer(rule)) {
      const tr = confirmedTransfer(rule, entry, amount, date);
      setTransfers((prev) => (prev.some((t) => t.id === tr.id) ? prev : [tr, ...prev]));
    } else {
      const tx = confirmedTransaction(rule, entry, amount, date);
      setTransactions((prev) => (prev.some((t) => t.id === tx.id) ? prev : [tx, ...prev]));
    }
    setPendingEntries((prev) => prev.filter((p) => p.id !== id));
  }

  function dismissPending(id: string) {
    setPendingEntries((prev) => prev.filter((p) => p.id !== id));
  }

  function setRecurringActive(id: string, active: boolean) {
    const today = toDateKey(new Date());
    setRecurringRules((prev) =>
      prev.map((r) => {
        if (r.id !== id) return r;
        const resumed = { ...r, active };
        return active ? skipToUpcoming(resumed, today) : resumed;
      }),
    );
  }

  function accountBalance(accountId: string) {
    const account = accounts.find((a) => a.id === accountId);
    const base = account?.initialBalance ?? 0;
    const fromTransactions = transactions
      .filter((t) => t.accountId === accountId)
      .reduce((sum, t) => sum + (t.type === 'credit' ? t.amount : -t.amount), base);
    // Transfers move money in/out of an account but are never income or spending.
    return transfers.reduce((sum, t) => {
      if (t.toAccountId === accountId) return sum + t.amount;
      if (t.fromAccountId === accountId) return sum - t.amount;
      return sum;
    }, fromTransactions);
  }

  function accountBalances() {
    return selectableAccounts.map((a) => ({ ...a, balance: accountBalance(a.id) }));
  }

  // Debt accounts hold what you owe; the Home total is only the money you actually have.
  const selectableAccounts = accounts.filter((a) => !a.hidden);
  const budgetEntries = useMemo(() => [...transactions, ...savedEntries(transfers)], [transactions, transfers]);
  const balance = selectableAccounts.reduce((sum, a) => sum + accountBalance(a.id), 0);

  function spentThisMonth(categoryId: string) {
    const nowKey = cycleOf(toDateKey(new Date()));
    return budgetEntries
      .filter((t) => t.categoryId === categoryId && t.type === 'debit' && cycleOf(t.date) === nowKey)
      .reduce((sum, t) => sum + t.amount, 0);
  }

  function totalIncomeThisMonth() {
    const nowKey = cycleOf(toDateKey(new Date()));
    return transactions.filter((t) => t.type === 'credit' && cycleOf(t.date) === nowKey).reduce((sum, t) => sum + t.amount, 0);
  }

  function totalSpendingThisMonth() {
    const nowKey = cycleOf(toDateKey(new Date()));
    return transactions.filter((t) => t.type === 'debit' && cycleOf(t.date) === nowKey).reduce((sum, t) => sum + t.amount, 0);
  }

  // Most recent transactions first, for the Home screen's short list.
  function recentTransactions(count = 10, accountId?: string) {
    return transactions
      .filter((t) => !accountId || t.accountId === accountId)
      .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0))
      .slice(0, count);
  }

  function categoryBreakdownThisMonth() {
    const nowKey = cycleOf(toDateKey(new Date()));
    const monthTxns = transactions.filter((t) => t.type === 'debit' && cycleOf(t.date) === nowKey);

    const totals = new Map<string, number>();
    monthTxns.forEach((t) => {
      totals.set(t.categoryId, (totals.get(t.categoryId) ?? 0) + t.amount);
    });
    const total = Array.from(totals.values()).reduce((a, b) => a + b, 0);

    return Array.from(totals.entries())
      .map(([categoryId, value]) => ({ categoryId, value, percent: total > 0 ? (value / total) * 100 : 0 }))
      .sort((a, b) => b.value - a.value);
  }

  // Monday -> Sunday for the week `weekOffset` weeks away from the current one.
  // weekOffset 0 = this week, -1 = last week, -2 = the week before that, ...
  function getWeekChartData(weekOffset: number, accountId?: string): ChartPoint[] {
    const now = new Date();
    const todayKey = toDateKey(now);
    const monday = startOfWeek(now);
    monday.setDate(monday.getDate() + weekOffset * 7);

    const points: ChartPoint[] = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date(monday);
      d.setDate(monday.getDate() + i);
      const key = toDateKey(d);
      const value = transactions
        .filter((t) => t.type === 'debit' && t.date === key && (!accountId || t.accountId === accountId))
        .reduce((sum, t) => sum + t.amount, 0);
      points.push({ key, label: weekdayShort(i), value, isToday: key === todayKey, isFuture: key > todayKey });
    }
    return points;
  }

  // Jan -> Dec of the current year (each point is one month's total spend).
  function getMonthChartData(accountId?: string): ChartPoint[] {
    const nowKey = cycleOf(toDateKey(new Date()));
    const year = Number(nowKey.slice(0, 4));
    const nowMonth = Number(nowKey.slice(5, 7)) - 1;
    const points: ChartPoint[] = Array.from({ length: 12 }, (_, i) => ({
      key: `${year}-${i}`,
      label: monthShort(i),
      value: 0,
      isFuture: i > nowMonth,
    }));

    transactions.forEach((t) => {
      if (accountId && t.accountId !== accountId) return;
      const k = cycleOf(t.date);
      if (t.type === 'debit' && Number(k.slice(0, 4)) === year) {
        points[Number(k.slice(5, 7)) - 1].value += t.amount;
      }
    });
    return points;
  }

  // One point per calendar year that has transactions, plus the current year
  // even if it's still empty, sorted oldest -> newest (e.g. 2025, 2026).
  function getYearChartData(accountId?: string): ChartPoint[] {
    const currentYear = Number(cycleOf(toDateKey(new Date())).slice(0, 4));
    const years = new Set<number>([currentYear]);
    transactions.forEach((t) => years.add(Number(cycleOf(t.date).slice(0, 4))));

    return Array.from(years)
      .sort((a, b) => a - b)
      .map((year) => {
        const value = transactions
          .filter(
            (t) =>
              t.type === 'debit' &&
              Number(cycleOf(t.date).slice(0, 4)) === year &&
              (!accountId || t.accountId === accountId),
          )
          .reduce((sum, t) => sum + t.amount, 0);
        return { key: String(year), label: String(year), value };
      });
  }

  function resetAllData() {
    setTransactions(initialTransactions);
    setAccounts(initialAccounts);
    setTransfers([]);
    setRecurringRules([]);
    setPendingEntries([]);
  }

  return (
    <TransactionsContext.Provider
      value={{
        ready: transactionsReady && recurringReady && pendingReady && transfersReady && accountsReady,
        transactions,
        addTransaction,
        addTransactions,
        deleteTransactions,
        updateTransaction,
        deleteTransaction,
        restoreTransaction,
        restoreTransfer,
        reorderAccounts,
        reassignCategory,
        balance,
        spentThisMonth,
        budgetEntries,
        categoryBreakdownThisMonth,
        totalIncomeThisMonth,
        totalSpendingThisMonth,
        recentTransactions,
        getWeekChartData,
        getMonthChartData,
        getYearChartData,
        accounts,
        selectableAccounts,
        addAccount,
        updateAccount,
        addAccounts,
        deleteAccount,
        accountBalance,
        accountBalances,
        transfers,
        addTransfer,
        updateTransfer,
        deleteTransfer,
        recurringRules,
        addRecurring,
        updateRecurring,
        deleteRecurring,
        setRecurringActive,
        pendingEntries,
        confirmPending,
        dismissPending,
        resetAllData,
      }}
    >
      {children}
    </TransactionsContext.Provider>
  );
}

export function useTransactions() {
  const ctx = useContext(TransactionsContext);
  if (!ctx) throw new Error('useTransactions must be used within TransactionsProvider');
  return ctx;
}
