import { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { AppState } from 'react-native';

import type { CardDesign } from '@/constants/card-styles';
import type { IconName } from '@/constants/categories';
import { useAuth } from '@/context/AuthContext';
import { usePersistedState } from '@/hooks/use-persisted-state';
import { confirmedTransaction, materializeRecurring, skipToUpcoming } from '@/utils/recurring';


export type TransactionType = 'debit' | 'credit';

export type AccountType = 'bank' | 'cash' | 'other';

export type Account = {
  id: string;
  name: string;
  type: AccountType;
  /** Name of a user-made type (stored with type 'other'); shown instead of the built-in label. */
  typeLabel?: string;
  icon: IconName;
  initialBalance: number; // starting balance before any tracked transactions
  // Card look + optional details (all optional so older accounts keep working)
  color?: string; // hex, e.g. '#2563EB'
  design?: CardDesign;
  provider?: string; // e.g. 'Maybank', 'TNG eWallet'
  last4?: string; // last 4 digits only, never a full number
};

export type TransactionItem = { id: string; label: string; amount: number };

export type Transaction = {
  id: string;
  title: string;
  date: string;
  categoryId: string;
  subcategory: string;
  amount: number;
  type: TransactionType;
  accountId: string;
  /** Optional line items, e.g. Nasi Lemak RM5, Service Charge RM0.50. */
  items?: TransactionItem[];
  /** Set when this transaction was generated by a recurring rule. */
  recurringId?: string;
};

/**
 * Money moved between two of the user's own accounts.
 * Deliberately NOT a Transaction: it changes each account's balance but is never
 * income or spending, so it can't distort budgets, charts or monthly totals.
 */
export type Transfer = {
  id: string;
  fromAccountId: string;
  toAccountId: string;
  amount: number;
  date: string; // YYYY-MM-DD
  note?: string;
};

export type RecurringFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

/**
 * fixed = the same amount is recorded automatically on each date.
 * ask   = on each date an entry WAITS for the user to type the real amount (salary that changes, utility bills).
 */
export type RecurringAmountMode = 'fixed' | 'ask';

/** A schedule that creates a real transaction each time it falls due. */
export type RecurringRule = {
  id: string;
  title: string;
  /** Fixed rules: the amount recorded. 'ask' rules: only an optional expected amount (0 = unknown). */
  amount: number;
  /** Missing on rules saved before this existed, which means 'fixed'. */
  amountMode?: RecurringAmountMode;
  type: TransactionType;
  categoryId: string;
  subcategory: string;
  accountId: string;
  frequency: RecurringFrequency;
  /** First occurrence. Also the anchor for "day of month" on monthly/yearly rules. */
  startDate: string;
  /** The next occurrence that has NOT been turned into a transaction yet. */
  nextDate: string;
  /** Optional last date (inclusive). */
  endDate?: string;
  active: boolean;
};

/**
 * A due occurrence of an 'ask' rule, waiting for the real amount.
 * It is NOT a transaction: it never touches balances, budgets or charts until the user confirms it.
 */
export type PendingEntry = { id: string; ruleId: string; date: string };

export type ChartPeriod = 'week' | 'month' | 'year';

export type ChartPoint = {
  key: string;
  label: string;
  value: number;
  /** true when this point represents "today" (only ever set for week points) */
  isToday?: boolean;
  isFuture?: boolean;
};

type TransactionsContextValue = {
  /** True once transactions, recurring rules and pending entries are all loaded from storage. */
  ready: boolean;
  transactions: Transaction[];
  addTransaction: (t: Omit<Transaction, 'id'>) => void;
  updateTransaction: (id: string, patch: Partial<Omit<Transaction, 'id'>>) => void;
  deleteTransaction: (id: string) => void;
  reassignCategory: (fromId: string, toId: string) => void;
  balance: number;
  spentThisMonth: (categoryId: string) => number;
  totalIncomeThisMonth: () => number;
  totalSpendingThisMonth: () => number;
  categoryBreakdownThisMonth: () => { categoryId: string; value: number; percent: number }[];
  /** Pass `accountId` to limit the list to one account (omit for all accounts). */
  recentTransactions: (count?: number, accountId?: string) => Transaction[];
  /** weekOffset: 0 = the week containing today, -1 = the week before that, etc. `accountId` limits to one account. */
  getWeekChartData: (weekOffset: number, accountId?: string) => ChartPoint[];
  /** Jan -> Dec of the current year */
  getMonthChartData: (accountId?: string) => ChartPoint[];
  /** one point per calendar year that has data (current year always included) */
  getYearChartData: (accountId?: string) => ChartPoint[];

  // Accounts (bank, cash, etc.)
  accounts: Account[];
  addAccount: (a: Omit<Account, 'id'>) => void;
  updateAccount: (id: string, patch: Partial<Omit<Account, 'id'>>) => void;
  /** Deletes the account and any transactions tied to it. */
  deleteAccount: (id: string) => void;
  accountBalance: (accountId: string) => number;
  /** Every account paired with its current computed balance — handy for the Assets tab. */
  accountBalances: () => (Account & { balance: number })[];

  // Transfers between accounts
  transfers: Transfer[];
  addTransfer: (t: Omit<Transfer, 'id'>) => void;
  updateTransfer: (id: string, patch: Partial<Omit<Transfer, 'id'>>) => void;
  deleteTransfer: (id: string) => void;

  // Recurring rules (transactions are generated automatically when they fall due)
  recurringRules: RecurringRule[];
  addRecurring: (r: Omit<RecurringRule, 'id'>) => void;
  updateRecurring: (id: string, patch: Partial<Omit<RecurringRule, 'id'>>) => void;
  deleteRecurring: (id: string) => void;
  /** Pause or resume. Resuming skips the paused period instead of back-filling it. */
  setRecurringActive: (id: string, active: boolean) => void;

  /** Due 'ask' occurrences waiting for the real amount. */
  pendingEntries: PendingEntry[];
  /** Records the real amount (and the date it actually arrived) and removes the entry. */
  confirmPending: (id: string, amount: number, date: string) => void;
  /** Drops the entry without recording anything (e.g. no salary this month). */
  dismissPending: (id: string) => void;

  resetAllData: () => void;
};

const TransactionsContext = createContext<TransactionsContextValue | undefined>(undefined);

const initialAccounts: Account[] = [
  { id: 'bank', name: 'Bank', type: 'bank', icon: 'business', initialBalance: 0 },
  { id: 'cash', name: 'Cash', type: 'cash', icon: 'cash', initialBalance: 0 },
];

const initialTransactions: Transaction[] = [];

// Monday-first, matching how the week chart is laid out.
const WEEKDAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const MONTH_LABELS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// Local-date key (avoids the UTC-shift you get from toISOString() near midnight).
function toDateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// Monday of the week containing `d`.
function startOfWeek(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay(); // 0 = Sun ... 6 = Sat
  const diffToMonday = day === 0 ? -6 : 1 - day;
  date.setDate(date.getDate() + diffToMonday);
  date.setHours(0, 0, 0, 0);
  return date;
}

export function TransactionsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [transactions, setTransactions, transactionsReady] = usePersistedState<Transaction[]>('transactions', initialTransactions, user?.id ?? null);
  const [accounts, setAccounts] = usePersistedState<Account[]>('accounts', initialAccounts, user?.id ?? null);
  const [transfers, setTransfers] = usePersistedState<Transfer[]>('transfers', [], user?.id ?? null);
  const [recurringRules, setRecurringRules, recurringReady] = usePersistedState<RecurringRule[]>('recurring', [], user?.id ?? null);
  const [pendingEntries, setPendingEntries, pendingReady] = usePersistedState<PendingEntry[]>('pending', [], user?.id ?? null);

  // Changes when the app returns to the foreground on a new day, so due rules are picked up
  // even if the app was left open overnight.
  const [todayKey, setTodayKey] = useState(() => toDateKey(new Date()));
  useEffect(() => {
    const sub = AppState.addEventListener('change', (state) => {
      if (state === 'active') setTodayKey(toDateKey(new Date()));
    });
    return () => sub.remove();
  }, []);

  // Turn due recurring occurrences into real transactions (fixed rules) or pending entries ('ask' rules).
  // Waits until ALL THREE lists have been loaded from storage: generating earlier would be overwritten by
  // the load that finishes afterwards.
  useEffect(() => {
    if (!transactionsReady || !recurringReady || !pendingReady) return;
    const { rules, created, pending } = materializeRecurring(recurringRules, transactions, todayKey, pendingEntries);
    if (created.length === 0 && pending.length === 0 && rules === recurringRules) return;
    if (created.length > 0) {
      setTransactions((prev) => {
        const have = new Set(prev.map((t) => t.id));
        const fresh = created.filter((t) => !have.has(t.id));
        return fresh.length > 0 ? [...fresh, ...prev] : prev;
      });
    }
    if (pending.length > 0) {
      setPendingEntries((prev) => {
        const have = new Set(prev.map((p) => p.id));
        const fresh = pending.filter((p) => !have.has(p.id));
        return fresh.length > 0 ? [...prev, ...fresh] : prev;
      });
    }
    setRecurringRules(rules);
  }, [
    transactionsReady,
    recurringReady,
    pendingReady,
    recurringRules,
    transactions,
    pendingEntries,
    todayKey,
    setTransactions,
    setPendingEntries,
    setRecurringRules,
  ]);

  function addTransaction(t: Omit<Transaction, 'id'>) {
    setTransactions((prev) => [{ ...t, id: Date.now().toString() }, ...prev]);
  }

  function updateTransaction(id: string, patch: Partial<Omit<Transaction, 'id'>>) {
    setTransactions((prev) => prev.map((t) => (t.id === id ? { ...t, ...patch } : t)));
  }

  function deleteTransaction(id: string) {
    setTransactions((prev) => prev.filter((t) => t.id !== id));
  }

  function reassignCategory(fromId: string, toId: string) {
    setTransactions((prev) => prev.map((t) => (t.categoryId === fromId ? { ...t, categoryId: toId } : t)));
  }

  function addAccount(a: Omit<Account, 'id'>) {
    setAccounts((prev) => [...prev, { ...a, id: Date.now().toString() }]);
  }

  function updateAccount(id: string, patch: Partial<Omit<Account, 'id'>>) {
    setAccounts((prev) => prev.map((acc) => (acc.id === id ? { ...acc, ...patch } : acc)));
  }

  function deleteAccount(id: string) {
    setAccounts((prev) => prev.filter((acc) => acc.id !== id));
    setTransactions((prev) => prev.filter((t) => t.accountId !== id));
    // A transfer needs both accounts, and a rule needs its account to post into.
    setTransfers((prev) => prev.filter((t) => t.fromAccountId !== id && t.toAccountId !== id));
    const orphanRuleIds = new Set(recurringRules.filter((r) => r.accountId === id).map((r) => r.id));
    setRecurringRules((prev) => prev.filter((r) => r.accountId !== id));
    setPendingEntries((prev) => prev.filter((p) => !orphanRuleIds.has(p.ruleId)));
  }

  function addTransfer(t: Omit<Transfer, 'id'>) {
    setTransfers((prev) => [{ ...t, id: `tr_${Date.now()}` }, ...prev]);
  }

  function updateTransfer(id: string, patch: Partial<Omit<Transfer, 'id'>>) {
    setTransfers((prev) => prev.map((t) => (t.id === id ? { ...t, ...patch } : t)));
  }

  function deleteTransfer(id: string) {
    setTransfers((prev) => prev.filter((t) => t.id !== id));
  }

  function addRecurring(r: Omit<RecurringRule, 'id'>) {
    setRecurringRules((prev) => [...prev, { ...r, id: `rule_${Date.now()}` }]);
  }

  function updateRecurring(id: string, patch: Partial<Omit<RecurringRule, 'id'>>) {
    setRecurringRules((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  }

  // Deleting a rule keeps the transactions it already created: they are real history.
  function deleteRecurring(id: string) {
    setRecurringRules((prev) => prev.filter((r) => r.id !== id));
    setPendingEntries((prev) => prev.filter((p) => p.ruleId !== id));
  }

  function confirmPending(id: string, amount: number, date: string) {
    const entry = pendingEntries.find((p) => p.id === id);
    const rule = entry ? recurringRules.find((r) => r.id === entry.ruleId) : undefined;
    if (!entry || !rule || !(amount > 0)) return;
    const tx = confirmedTransaction(rule, entry, amount, date);
    setTransactions((prev) => (prev.some((t) => t.id === tx.id) ? prev : [tx, ...prev]));
    setPendingEntries((prev) => prev.filter((p) => p.id !== id));
  }

  function dismissPending(id: string) {
    setPendingEntries((prev) => prev.filter((p) => p.id !== id));
  }

  function setRecurringActive(id: string, active: boolean) {
    const today = toDateKey(new Date());
    setRecurringRules((prev) =>
      prev.map((r) => {
        if (r.id !== id) return r;
        const resumed = { ...r, active };
        return active ? skipToUpcoming(resumed, today) : resumed;
      }),
    );
  }

  function accountBalance(accountId: string) {
    const account = accounts.find((a) => a.id === accountId);
    const base = account?.initialBalance ?? 0;
    const fromTransactions = transactions
      .filter((t) => t.accountId === accountId)
      .reduce((sum, t) => sum + (t.type === 'credit' ? t.amount : -t.amount), base);
    // Transfers move money in/out of an account but are never income or spending.
    return transfers.reduce((sum, t) => {
      if (t.toAccountId === accountId) return sum + t.amount;
      if (t.fromAccountId === accountId) return sum - t.amount;
      return sum;
    }, fromTransactions);
  }

  function accountBalances() {
    return accounts.map((a) => ({ ...a, balance: accountBalance(a.id) }));
  }

  const balance = accounts.reduce((sum, a) => sum + accountBalance(a.id), 0);

  function spentThisMonth(categoryId: string) {
    const now = new Date();
    return transactions
      .filter((t) => {
        const d = new Date(t.date);
        return (
          t.categoryId === categoryId &&
          t.type === 'debit' &&
          d.getMonth() === now.getMonth() &&
          d.getFullYear() === now.getFullYear()
        );
      })
      .reduce((sum, t) => sum + t.amount, 0);
  }

  function totalIncomeThisMonth() {
    const now = new Date();
    return transactions
      .filter((t) => {
        const d = new Date(t.date);
        return t.type === 'credit' && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
      })
      .reduce((sum, t) => sum + t.amount, 0);
  }

  function totalSpendingThisMonth() {
    const now = new Date();
    return transactions
      .filter((t) => {
        const d = new Date(t.date);
        return t.type === 'debit' && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
      })
      .reduce((sum, t) => sum + t.amount, 0);
  }

  // Most recent transactions first, for the Home screen's short list.
  function recentTransactions(count = 10, accountId?: string) {
    return transactions
      .filter((t) => !accountId || t.accountId === accountId)
      .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0))
      .slice(0, count);
  }

  function categoryBreakdownThisMonth() {
    const now = new Date();
    const monthTxns = transactions.filter((t) => {
      const d = new Date(t.date);
      return t.type === 'debit' && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
    });

    const totals = new Map<string, number>();
    monthTxns.forEach((t) => {
      totals.set(t.categoryId, (totals.get(t.categoryId) ?? 0) + t.amount);
    });
    const total = Array.from(totals.values()).reduce((a, b) => a + b, 0);

    return Array.from(totals.entries())
      .map(([categoryId, value]) => ({ categoryId, value, percent: total > 0 ? (value / total) * 100 : 0 }))
      .sort((a, b) => b.value - a.value);
  }

  // Monday -> Sunday for the week `weekOffset` weeks away from the current one.
  // weekOffset 0 = this week, -1 = last week, -2 = the week before that, ...
  function getWeekChartData(weekOffset: number, accountId?: string): ChartPoint[] {
    const now = new Date();
    const todayKey = toDateKey(now);
    const monday = startOfWeek(now);
    monday.setDate(monday.getDate() + weekOffset * 7);

    const points: ChartPoint[] = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date(monday);
      d.setDate(monday.getDate() + i);
      const key = toDateKey(d);
      const value = transactions
        .filter((t) => t.type === 'debit' && t.date === key && (!accountId || t.accountId === accountId))
        .reduce((sum, t) => sum + t.amount, 0);
      points.push({ key, label: WEEKDAY_LABELS[i], value, isToday: key === todayKey, isFuture: key > todayKey });
    }
    return points;
  }

  // Jan -> Dec of the current year (each point is one month's total spend).
  function getMonthChartData(accountId?: string): ChartPoint[] {
    const now = new Date();
    const year = now.getFullYear();
    const points: ChartPoint[] = MONTH_LABELS.map((label, i) => ({
      key: `${year}-${i}`,
      label,
      value: 0,
      isFuture: i > now.getMonth(),
    }));

    transactions.forEach((t) => {
      if (accountId && t.accountId !== accountId) return;
      const d = new Date(t.date);
      if (t.type === 'debit' && d.getFullYear() === year) {
        points[d.getMonth()].value += t.amount;
      }
    });
    return points;
  }

  // One point per calendar year that has transactions, plus the current year
  // even if it's still empty, sorted oldest -> newest (e.g. 2025, 2026).
  function getYearChartData(accountId?: string): ChartPoint[] {
    const currentYear = new Date().getFullYear();
    const years = new Set<number>([currentYear]);
    transactions.forEach((t) => years.add(new Date(t.date).getFullYear()));

    return Array.from(years)
      .sort((a, b) => a - b)
      .map((year) => {
        const value = transactions
          .filter(
            (t) =>
              t.type === 'debit' &&
              new Date(t.date).getFullYear() === year &&
              (!accountId || t.accountId === accountId),
          )
          .reduce((sum, t) => sum + t.amount, 0);
        return { key: String(year), label: String(year), value };
      });
  }

  function resetAllData() {
    setTransactions(initialTransactions);
    setAccounts(initialAccounts);
    setTransfers([]);
    setRecurringRules([]);
    setPendingEntries([]);
  }

  return (
    <TransactionsContext.Provider
      value={{
        ready: transactionsReady && recurringReady && pendingReady,
        transactions,
        addTransaction,
        updateTransaction,
        deleteTransaction,
        reassignCategory,
        balance,
        spentThisMonth,
        categoryBreakdownThisMonth,
        totalIncomeThisMonth,
        totalSpendingThisMonth,
        recentTransactions,
        getWeekChartData,
        getMonthChartData,
        getYearChartData,
        accounts,
        addAccount,
        updateAccount,
        deleteAccount,
        accountBalance,
        accountBalances,
        transfers,
        addTransfer,
        updateTransfer,
        deleteTransfer,
        recurringRules,
        addRecurring,
        updateRecurring,
        deleteRecurring,
        setRecurringActive,
        pendingEntries,
        confirmPending,
        dismissPending,
        resetAllData,
      }}
    >
      {children}
    </TransactionsContext.Provider>
  );
}

export function useTransactions() {
  const ctx = useContext(TransactionsContext);
  if (!ctx) throw new Error('useTransactions must be used within TransactionsProvider');
  return ctx;
}
